changelog:
  exclude:
    labels:
      - documentation
  categories:
    - title: Несовместимые изменения 🛠
      labels:
        - Semver-Major
    - title: Улучшили 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Алгоритмы
      labels:
        - algorithm
    - title: Контейнеры
      labels:
        - container
    - title: Остальные изменения
      labels:
        - "*"
